### ISSUE TITLE
2️⃣ [BUG] 🐛 Aucun résultat sur la page "Trouver une mission" de l'application mobile C&C coté intervenant

### ISSUE THREAD

**Issue by maria-rock** [clickandcare/tickets#10]
### Doublon ?

- [X] J'ai vérifié que ce bug n'a pas été signalé via une autre issue

### Application(s) <label>

Mobile Android

### Personae <label>

Interne - Admin

### Criticité <label>

Bloquant

### Fréquence <label>

Systématique (Facilement reproductible)

### Situation rencontrée

1. En tant qu'intervenant
2. Je vais sur le menu burger
3. Je clique sur "Trouver une mission"
4. ❌ page blanche avec le titre "Trouver une mission" et l'icône du menu

### Situation attendue

4. avoir un onglet "offre d'emploi" et un onglet "Mes alertes"

### Capture(s) d'écran / vidéo / log / lien(s)

![MicrosoftTeams-image](https://user-images.githubusercontent.com/115983847/196991175-7bd9555f-e44b-462f-acdd-43eaf04666e7.png)

### Version de l'application

beta

**Comment by JustinMartinDev** [comment]
manque un critère de recherche ??? dans le back

**Comment by JustinMartinDev** [comment]
https://sentry.io/organizations/click-and-care/issues/3568485199/?project=5908394&query=is%3Aunresolved&referrer=issue-stream

Ajouter une valeur par défaut pour startDateCriteria : now
