### ISSUE TITLE
[BUG] 🐛 Problème de menu déroulant lors de l'ajout 

### ISSUE THREAD

**Issue by maria-rock** [clickandcare/tickets#14]
### Doublon ?

- [X] J'ai vérifié que ce bug n'a pas été signalé via une autre issue

### Application(s) <label>

Mobile Android

### Personae <label>

Interne - Admin

### Criticité <label>

Non bloquant

### Fréquence <label>

Aléatoire (Difficilement reproductible)

### Situation rencontrée

1. En tant qu'Intervenant
2. Je vais sur le menu
3. Je clique sur "mon profil candidat"
4. Je vais sur "Mon identité"
5. Je passe la page de renseignement
6. Sur la page "Ajouter vos justificatifs", je clique sur "Ajouter" du bloc pièce d'identité
7. ❌ problème sur le menu déroulant

### Situation attendue

7. un menu déroulant avec Carte Nationale d'identité, passeport, permis de conduire, titre de séjour

### Capture(s) d'écran / vidéo / log / lien(s)

![MicrosoftTeams-image](https://user-images.githubusercontent.com/115983847/198659186-62cafa94-6004-4a1e-873f-29dc52274e41.png)

### Version de l'application

beta

**Comment by JustinMartinDev** [comment]
Faudrait essayer en forçant l'utilisation de la dernière updates dans Expo Go

**Comment by benoitbouffard** [comment]
@JustinMartinDev @maria-rock je n arrive pas a reproduire ce problème en utilisant la dernière version de l'application via expo go. @maria-rock peux tu nous confirmer que tu utilise bien la derniere version de expo go ?

**Comment by JustinMartinDev** [comment]
a été fix

**Comment by gauthieramano** [comment]
Bug toujours présent
