### ISSUE TITLE
[BUG] 🐛 ETQ CSM, lorsque je tente d'avoir accès aux missions proposées pour un intervenant, je n'y ai pas accès

### ISSUE THREAD

**Issue by naomiclickandcare** [clickandcare/tickets#16]
### Doublon ?

- [X] J'ai vérifié que ce bug n'a pas été signalé via une autre issue

### Application(s) <label>

Back-office (Forest Admin)

### Personae <label>

Interne - CSM

### Criticité <label>

Non bloquant

### Fréquence <label>

Systématique (Facilement reproductible)

### Situation rencontrée

1. En tant que CSM à RABAT
2. Dans la collection Intervenants, lorsque je souhaite accéder à la related data " annonces proposées"
3. Le message "Collection access forbidden" apparaît 
[cap 2.pdf](https://github.com/clickandcare/tickets/files/9921786/cap.2.pdf)

### Situation attendue

4. Avoir accès à l'ensemble des missions proposées à l'intervenant

### Type de navigateur

Mozilla Firefox

**Comment by benoitbouffard** [comment]
@naomiclickandcare peux tu préciser 
1) Quelle est la fiche intervenant que tu as consulté 'ajouter l'id ou l'url)
2) le problème est il uniqument pour les rabati ou toi aussi ? 
3) j'ai changé les permissions pour les staffeurs, normalement le problème devait etre corrigé

**Comment by naomiclickandcare** [comment]
1. [👩‍⚕️ Intervenants](https://app.forestadmin.com/click-and-care-backoffice/Preprod/ClicknCare/data/care-giver/index)
/
[Justin Martin - 7](https://app.forestadmin.com/click-and-care-backoffice/Preprod/ClicknCare/data/care-giver/index/record/care-giver/44f1025a-db20-4988-a7b4-109b80961254/summary)

2. Uniquement pour les Rabatis 

3. Je confirme: @benoitbouffard  problème corrigé !
