### ISSUE TITLE
[BUG] 🐛 ETQ CSM RABAT, je ne peux pas modifier certaines informations dans le summary d'une fiche intervenant

### ISSUE THREAD

**Issue by naomiclickandcare** [clickandcare/tickets#17]
### Doublon ?

- [X] J'ai vérifié que ce bug n'a pas été signalé via une autre issue

### Application(s) <label>

Back-office (Forest Admin)

### Personae <label>

Interne - CSM

### Criticité <label>

Bloquant

### Fréquence <label>

Aléatoire (Difficilement reproductible)

### Situation rencontrée

1. En tant que CSM à RABAT
2. Lorsque je clique sur une fiche Intervenant puis que je fais Edit au niveau du Summary
3. Je ne peux pas modifier et enregistrer les informations suivantes: tout dans la case "coordonées", num de sécurité sociale et num Siret dans la case "Administration"

### Situation attendue

4. Pourvoir modifier ces informations

### Type de navigateur

Mozilla Firefox

**Comment by benoitbouffard** [comment]
@naomiclickandcare  ja i fait des changements au niveau des droits est ce bon ?

**Comment by naomiclickandcare** [comment]
@benoitbouffard Oui c'est bon :)
