### ISSUE TITLE
[BUG] 🐛 ETQ CSM, j'effectue une recherche via la collection intervenant et aucun profil correspondant aux critères n'est remonté 

### ISSUE THREAD

**Issue by naomiclickandcare** [clickandcare/tickets#21]
### Doublon ?

- [X] J'ai vérifié que ce bug n'a pas été signalé via une autre issue

### Application(s) <label>

Back-office (Forest Admin)

### Personae <label>

Interne - CSM

### Criticité <label>

Bloquant

### Fréquence <label>

Systématique (Facilement reproductible)

### Situation rencontrée

1. En tant que CSM
2. Aller dans la collection Intervenant
3. Je clique sur le bouton "Action" 
4. Je clique sur "Démarrer une recherche" 
5. Je mets comme critères:
![image](https://user-images.githubusercontent.com/115176984/200286284-60f06f60-1848-4a9c-82f5-e3ab2582d876.png)
6. ❌Le message "no intervenants match your filters" : 
![image](https://user-images.githubusercontent.com/115176984/200286403-2d0732fa-a14b-4595-8be0-7a0a42312a2f.png)
7. Nous avons pourtant des intervenants qui devraient matcher et être remontés: ex - [👩‍⚕️ Intervenants](https://app.forestadmin.com/click-and-care-backoffice/Preprod/ClicknCare/data/care-giver/index?search=221111)
/
[Benoit Bouffard test - 221111](https://app.forestadmin.com/click-and-care-backoffice/Preprod/ClicknCare/data/care-giver/index/record/care-giver/5c6e5d62-2f3d-4f01-95f3-f971e79f3388/summary?search=221111)

### Situation attendue

8. Que les profils correspondant aux filtres remontent 

### Type de navigateur

Mozilla Firefox

**Comment by oliv1008** [comment]
Bug déjà résolu par la PR 
- https://github.com/clickandcare/apps/pull/158
