### ISSUE TITLE
[BUG] 🐛 Fonction "réinitialiser mon mot de passe" ne fonction pas 

### ISSUE THREAD

**Issue by maria-rock** [clickandcare/tickets#23]
### Doublon ?

- [X] J'ai vérifié que ce bug n'a pas été signalé via une autre issue

### Application(s) <label>

Mobile Android

### Personae <label>

Interne - Admin

### Criticité <label>

Bloquant

### Fréquence <label>

Systématique (Facilement reproductible)

### Situation rencontrée

1. en tant qu'intervenant
2. Je vais sur me connecter
3. Je clic sur "Mot de passe oublié"
4. J'inscris mon email
5. Puis je clic sur 'Réinitialiser mon mot de passe" ❌
_message afficher : Impossible d'envoyer votre code de sécurité avec cette adresse email, veuillez vérifier l'adresse indiquée._

Ne fonctionne pas sur : maria.rock@clickandcare.fr
marketing@clickandcare.fr

### Situation attendue

5. envoyer d'un code sur l'email indiquée

### Capture(s) d'écran / vidéo / log / lien(s)

![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/115983847/201115635-3b86ce7a-8ce5-4b19-a948-9a073c74a185.png)

**Comment by benoitbouffard** [comment]
@maria-rock je viens de tester avec l'adresse marketing@clickandcare.fr et j'ai bien recu le mail de récup de mot de passe.
Pour info j'ai définis le mot de passe à Cc0642015960$
